fn main(){
    for(int i = 0; i < 6; i++){
        switch(i){
            case 0:
                write("i = 0\n");
                break;
            case 1:
                write("i = 1\n");
                break;
            case 2:
                write("i = 2\n");
                break;
            case 3:
                write("i = 3\n");
                break;
            case 4:
                write("i = 4\n");
                break;
            case 5:
                write("i = 5\n");
                break;
        }
    }
}