import io

fn main(args){
    string forget_char_arrays = "I HATE CHAR ARRAYS";
    write(forget_char_arrays);

    forget_char_arrays += ", CHAR ARRAYS SUCK";
    write(forget_char_arrays);

    bool test = false;
    switch(test){
        case 0:
            write("false\n");
            break;
        case 1:
            write("true\n");
            break;
    }

    C{
        int twelve = 12;
    };

    twelve += 1;
    write(twelve);
}